// Generated by AshTypescript - Shared Types
// Do not edit this file manually



export type UUID = string;
export type UtcDateTimeUsec = string;

// ApiKey Schema
export type ApiKeyResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "expiresAt" | "insertedAt" | "updatedAt" | "valid";
  id: UUID;
  name: string | null;
  expiresAt: UtcDateTimeUsec;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  valid: boolean | null;
};



export type ApiKeyAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "expiresAt" | "insertedAt" | "updatedAt";
  id: UUID;
  name: string | null;
  expiresAt: UtcDateTimeUsec;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// User Schema
export type UserResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email" | "name" | "role" | "active" | "insertedAt" | "updatedAt";
  id: UUID;
  email: string;
  name: string | null;
  role: "admin" | "user";
  active: boolean;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  userSummary: { __type: "ComplexCalculation"; __returnType: {id: UUID, email: string, name: string | null, __type: "TypedMap", __primitiveFields: "id" | "email" | "name"} | null; };
};



export type UserAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email" | "name" | "role" | "active" | "insertedAt" | "updatedAt";
  id: UUID;
  email: string;
  name: string | null;
  role: "admin" | "user";
  active: boolean;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// AccessLog Schema
export type AccessLogResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "actionType" | "actionName" | "resourceType" | "recordId" | "projectId" | "actorId" | "actorEmail" | "ipAddress" | "userAgent" | "requestId" | "requestPath" | "pageViewId" | "occurredAt";
  id: UUID;
  actionType: "create" | "destroy" | "read" | "update";
  actionName: string;
  resourceType: string;
  recordId: UUID | null;
  projectId: UUID | null;
  actorId: UUID | null;
  actorEmail: string | null;
  ipAddress: string | null;
  userAgent: string | null;
  requestId: string | null;
  requestPath: string | null;
  pageViewId: string | null;
  occurredAt: UtcDateTimeUsec;
};



export type AccessLogAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "actionType" | "actionName" | "resourceType" | "recordId" | "projectId" | "actorId" | "actorEmail" | "ipAddress" | "userAgent" | "requestId" | "requestPath" | "pageViewId" | "occurredAt";
  id: UUID;
  actionType: "create" | "destroy" | "read" | "update";
  actionName: string;
  resourceType: string;
  recordId: UUID | null;
  projectId: UUID | null;
  actorId: UUID | null;
  actorEmail: string | null;
  ipAddress: string | null;
  userAgent: string | null;
  requestId: string | null;
  requestPath: string | null;
  pageViewId: string | null;
  occurredAt: UtcDateTimeUsec;
};


// Memory Schema
export type MemoryResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "scope" | "repoKey" | "content" | "insertedAt" | "updatedAt" | "createdById";
  id: UUID;
  scope: "global" | "repository" | "user";
  repoKey: string | null;
  content: string;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  createdById: UUID;
  createdBy: { __type: "Relationship"; __resource: UserResourceSchema; };
};



export type MemoryAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "scope" | "repoKey" | "content" | "insertedAt" | "updatedAt" | "createdById";
  id: UUID;
  scope: "global" | "repository" | "user";
  repoKey: string | null;
  content: string;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  createdById: UUID;
};


// AnthropicConfig Schema
export type AnthropicConfigResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "defaultModel" | "apiKeySet";
  id: UUID;
  defaultModel: string | null;
  apiKeySet: boolean | null;
};



export type AnthropicConfigAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "defaultModel";
  id: UUID;
  defaultModel: string | null;
};


// GcsConfig Schema
export type GcsConfigResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "bucketName" | "serviceAccountJsonSet";
  id: UUID;
  bucketName: string | null;
  serviceAccountJsonSet: boolean | null;
};



export type GcsConfigAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "bucketName";
  id: UUID;
  bucketName: string | null;
};


export type ApiKeyFilterInput = {
  and?: Array<ApiKeyFilterInput>;
  or?: Array<ApiKeyFilterInput>;
  not?: Array<ApiKeyFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  expiresAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  valid?: {
    eq?: boolean;
    notEq?: boolean;
    isNil?: boolean;
  };



};
export type UserFilterInput = {
  and?: Array<UserFilterInput>;
  or?: Array<UserFilterInput>;
  not?: Array<UserFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  email?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  role?: {
    eq?: "admin" | "user";
    notEq?: "admin" | "user";
    in?: Array<"admin" | "user">;
  };

  active?: {
    eq?: boolean;
    notEq?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  userSummary?: {
    eq?: {id: UUID, email: string, name: string | null, __type: "TypedMap", __primitiveFields: "id" | "email" | "name"};
    notEq?: {id: UUID, email: string, name: string | null, __type: "TypedMap", __primitiveFields: "id" | "email" | "name"};
    in?: Array<{id: UUID, email: string, name: string | null, __type: "TypedMap", __primitiveFields: "id" | "email" | "name"}>;
    isNil?: boolean;
  };



};
export type AccessLogFilterInput = {
  and?: Array<AccessLogFilterInput>;
  or?: Array<AccessLogFilterInput>;
  not?: Array<AccessLogFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  actionType?: {
    eq?: "create" | "destroy" | "read" | "update";
    notEq?: "create" | "destroy" | "read" | "update";
    in?: Array<"create" | "destroy" | "read" | "update">;
  };

  actionName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  resourceType?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  recordId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };

  projectId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };

  actorId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };

  actorEmail?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  ipAddress?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  userAgent?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  requestId?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  requestPath?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  pageViewId?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  occurredAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type MemoryFilterInput = {
  and?: Array<MemoryFilterInput>;
  or?: Array<MemoryFilterInput>;
  not?: Array<MemoryFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  scope?: {
    eq?: "global" | "repository" | "user";
    notEq?: "global" | "repository" | "user";
    in?: Array<"global" | "repository" | "user">;
  };

  repoKey?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  content?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  createdById?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };


  createdBy?: UserFilterInput;

};
export type AnthropicConfigFilterInput = {
  and?: Array<AnthropicConfigFilterInput>;
  or?: Array<AnthropicConfigFilterInput>;
  not?: Array<AnthropicConfigFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  defaultModel?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  apiKeySet?: {
    eq?: boolean;
    notEq?: boolean;
    isNil?: boolean;
  };



};
export type GcsConfigFilterInput = {
  and?: Array<GcsConfigFilterInput>;
  or?: Array<GcsConfigFilterInput>;
  not?: Array<GcsConfigFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  bucketName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  serviceAccountJsonSet?: {
    eq?: boolean;
    notEq?: boolean;
    isNil?: boolean;
  };



};


export const apiKeyFilterFields = ["id", "name", "expiresAt", "insertedAt", "updatedAt", "valid"] as const;
export type ApiKeyFilterField = (typeof apiKeyFilterFields)[number];

export const userFilterFields = ["id", "email", "name", "role", "active", "insertedAt", "updatedAt", "userSummary"] as const;
export type UserFilterField = (typeof userFilterFields)[number];

export const accessLogFilterFields = ["id", "actionType", "actionName", "resourceType", "recordId", "projectId", "actorId", "actorEmail", "ipAddress", "userAgent", "requestId", "requestPath", "pageViewId", "occurredAt"] as const;
export type AccessLogFilterField = (typeof accessLogFilterFields)[number];

export const memoryFilterFields = ["id", "scope", "repoKey", "content", "insertedAt", "updatedAt", "createdById", "createdBy"] as const;
export type MemoryFilterField = (typeof memoryFilterFields)[number];

export const anthropicConfigFilterFields = ["id", "defaultModel", "apiKeySet"] as const;
export type AnthropicConfigFilterField = (typeof anthropicConfigFilterFields)[number];

export const gcsConfigFilterFields = ["id", "bucketName", "serviceAccountJsonSet"] as const;
export type GcsConfigFilterField = (typeof gcsConfigFilterFields)[number];


export const apiKeySortFields = ["id", "name", "expiresAt", "insertedAt", "updatedAt", "valid"] as const;
export type ApiKeySortField = (typeof apiKeySortFields)[number];

export const userSortFields = ["id", "email", "name", "role", "active", "insertedAt", "updatedAt", "userSummary"] as const;
export type UserSortField = (typeof userSortFields)[number];

export const accessLogSortFields = ["id", "actionType", "actionName", "resourceType", "recordId", "projectId", "actorId", "actorEmail", "ipAddress", "userAgent", "requestId", "requestPath", "pageViewId", "occurredAt"] as const;
export type AccessLogSortField = (typeof accessLogSortFields)[number];

export const memorySortFields = ["id", "scope", "repoKey", "content", "insertedAt", "updatedAt", "createdById"] as const;
export type MemorySortField = (typeof memorySortFields)[number];

export const anthropicConfigSortFields = ["id", "defaultModel", "apiKeySet"] as const;
export type AnthropicConfigSortField = (typeof anthropicConfigSortFields)[number];

export const gcsConfigSortFields = ["id", "bucketName", "serviceAccountJsonSet"] as const;
export type GcsConfigSortField = (typeof gcsConfigSortFields)[number];


// Utility Types

// Sort string type — allows optional direction prefix on sort field names
// Prefixes per Ash.Query.sort/3: + (asc), - (desc), ++ (asc_nils_first), -- (desc_nils_last)
export type SortString<T extends string> = T | `+${T}` | `-${T}` | `++${T}` | `--${T}`;

// Resource schema constraint
export type TypedSchema = {
  __type: "Resource" | "TypedMap" | "Union";
  __primitiveFields: string;
};

// Utility type to convert union to intersection
export type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Helper type to infer union field values, avoiding duplication between array and non-array unions
export type InferUnionFieldValue<
  UnionSchema extends { __type: "Union"; __primitiveFields: any },
  FieldSelection extends any[],
> = UnionToIntersection<
  {
    [FieldIndex in keyof FieldSelection]: FieldSelection[FieldIndex] extends UnionSchema["__primitiveFields"]
      ? FieldSelection[FieldIndex] extends keyof UnionSchema
        ? { [P in FieldSelection[FieldIndex]]: UnionSchema[FieldSelection[FieldIndex]] }
        : never
      : FieldSelection[FieldIndex] extends Record<string, any>
        ? {
            [UnionKey in keyof FieldSelection[FieldIndex]]: UnionKey extends keyof UnionSchema
              ? NonNullable<UnionSchema[UnionKey]> extends { __array: true; __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                ? FieldSelection[FieldIndex][UnionKey] extends any[]
                  ? Array<
                      UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      >
                    > | null
                  : never
                : NonNullable<UnionSchema[UnionKey]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                  ? FieldSelection[FieldIndex][UnionKey] extends any[]
                    ? UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      > | null
                    : never
                  : NonNullable<UnionSchema[UnionKey]> extends TypedSchema
                    ? InferResult<NonNullable<UnionSchema[UnionKey]>, FieldSelection[FieldIndex][UnionKey]>
                    : never
              : never;
          }
        : never;
  }[number]
>;

export type HasComplexFields<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
> extends never
  ? false
  : true;

export type ComplexFieldKeys<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
>;

export type LeafFieldSelection<T extends TypedSchema> = T["__primitiveFields"];

export type ComplexFieldSelection<T extends TypedSchema> = {
  [K in ComplexFieldKeys<T>]?: T[K] extends {
    __type: "Relationship";
    __resource: infer Resource;
  }
    ? NonNullable<Resource> extends TypedSchema
      ? UnifiedFieldSelection<NonNullable<Resource>>[]
      : never
    : T[K] extends {
          __type: "ComplexCalculation";
          __returnType: infer ReturnType;
        }
      ? T[K] extends { __args: infer Args }
        ? NonNullable<ReturnType> extends TypedSchema
          ? {
              args: Args;
              fields: UnifiedFieldSelection<NonNullable<ReturnType>>[];
            }
          : { args: Args }
        : NonNullable<ReturnType> extends TypedSchema
          ? { fields: UnifiedFieldSelection<NonNullable<ReturnType>>[] }
          : never
      : T[K] extends { __type: "TypedMap" }
        ? NonNullable<T[K]> extends TypedSchema
          ? UnifiedFieldSelection<NonNullable<T[K]>>[]
          : never
        : T[K] extends { __type: "Union"; __primitiveFields: infer PrimitiveFields }
          ? T[K] extends { __array: true }
            ? (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields" | "__array">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : NonNullable<T[K]> extends TypedSchema
              ? UnifiedFieldSelection<NonNullable<T[K]>>[]
              : never;
};

// Main type: Use explicit base case detection to prevent infinite recursion
export type UnifiedFieldSelection<T extends TypedSchema> =
  HasComplexFields<T> extends false
    ? LeafFieldSelection<T> // Base case: only primitives, no recursion
    : LeafFieldSelection<T> | ComplexFieldSelection<T>; // Recursive case

export type InferFieldValue<
  T extends TypedSchema,
  Field,
> = Field extends T["__primitiveFields"]
  ? Field extends keyof T
    ? { [K in Field]: T[Field] }
    : never
  : Field extends Record<string, any>
    ? {
        [K in keyof Field]: K extends keyof T
          ? T[K] extends {
              __type: "Relationship";
              __resource: infer Resource;
            }
            ? NonNullable<Resource> extends TypedSchema
              ? T[K] extends { __array: true }
                ? Array<InferResult<NonNullable<Resource>, Field[K]>>
                : null extends Resource
                  ? InferResult<NonNullable<Resource>, Field[K]> | null
                  : InferResult<NonNullable<Resource>, Field[K]>
            : never
          : T[K] extends {
                __type: "ComplexCalculation";
                __returnType: infer ReturnType;
              }
            ? NonNullable<ReturnType> extends TypedSchema
              ? null extends ReturnType
                ? InferResult<NonNullable<ReturnType>, Field[K]["fields"]> | null
                : InferResult<NonNullable<ReturnType>, Field[K]["fields"]>
              : ReturnType
            : NonNullable<T[K]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
              ? NonNullable<T[K]> extends { __array: true }
                ? Field[K] extends any[]
                  ? null extends T[K]
                    ? Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      > | null
                    : Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      >
                  : never
                : Field[K] extends any[]
                  ? null extends T[K]
                    ? UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof NonNullable<T[K]>
                                ? { [P in E]: NonNullable<T[K]>[P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      > | null
                    : UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof T[K]
                                ? { [P in E]: T[K][P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      >
                  : never
              : T[K] extends { __type: "Union"; __primitiveFields: any }
                ? T[K] extends { __array: true }
                  ? Field[K] extends any[]
                    ? null extends T[K]
                      ? Array<InferUnionFieldValue<T[K], Field[K]>> | null
                      : Array<InferUnionFieldValue<T[K], Field[K]>>
                    : never
                  : Field[K] extends any[]
                    ? null extends T[K]
                      ? InferUnionFieldValue<T[K], Field[K]> | null
                      : InferUnionFieldValue<T[K], Field[K]>
                    : never
                  : NonNullable<T[K]> extends TypedSchema
                    ? null extends T[K]
                      ? InferResult<NonNullable<T[K]>, Field[K]> | null
                      : InferResult<NonNullable<T[K]>, Field[K]>
                    : never
          : never;
      }
    : never;

export type InferResult<
  T extends TypedSchema,
  SelectedFields extends UnifiedFieldSelection<T>[] | undefined,
> = SelectedFields extends undefined
  ? {}
  : SelectedFields extends []
  ? {}
  : SelectedFields extends UnifiedFieldSelection<T>[]
  ? UnionToIntersection<
      {
        [K in keyof SelectedFields]: InferFieldValue<T, SelectedFields[K]>;
      }[number]
    >
  : {};

// Pagination conditional types
// Checks if a page configuration object has any pagination parameters
export type HasPaginationParams<Page> =
  Page extends { offset: any } ? true :
  Page extends { after: any } ? true :
  Page extends { before: any } ? true :
  false;

// Infer which pagination type is being used from the page config
export type InferPaginationType<Page> =
  Page extends { offset: any } ? "offset" :
  Page extends { after: any } | { before: any } ? "keyset" :
  never;

// Returns either non-paginated (array) or paginated result based on page params
// For single pagination type support (offset-only or keyset-only)
// @ts-ignore
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export type ConditionalPaginatedResult<
  Page,
  RecordType,
  PaginatedType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? PaginatedType
    : RecordType;

// For actions supporting both offset and keyset pagination
// Infers the specific pagination type based on which params were passed
export type ConditionalPaginatedResultMixed<
  Page,
  RecordType,
  OffsetType,
  KeysetType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? InferPaginationType<Page> extends "offset"
      ? OffsetType
      : InferPaginationType<Page> extends "keyset"
        ? KeysetType
        : OffsetType | KeysetType  // Fallback to union if can't determine
    : RecordType;

export type SuccessDataFunc<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: true }
>["data"];


export type ErrorData<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: false }
>["errors"];

/**
 * Represents an error from an unsuccessful RPC call.
 *
 * This type matches the error structure defined in the AshTypescript.Rpc.Error protocol.
 *
 * @example
 * const error: AshRpcError = {
 *   type: "invalid_changes",
 *   message: "Invalid value for field %{field}",
 *   shortMessage: "Invalid changes",
 *   vars: { field: "email" },
 *   fields: ["email"],
 *   path: ["user", "email"],
 *   details: { suggestion: "Provide a valid email address" }
 * }
 */
export type AshRpcError = {
  /** Machine-readable error type (e.g., "invalid_changes", "not_found") */
  type: string;
  /** Full error message (may contain template variables like %{key}) */
  message: string;
  /** Concise version of the message */
  shortMessage: string;
  /** Variables to interpolate into the message template */
  vars: Record<string, any>;
  /** List of affected field names (for field-level errors) */
  fields: string[];
  /** Path to the error location in the data structure */
  path: string[];
  /** Optional map with extra details (e.g., suggestions, hints) */
  details?: Record<string, any>;
}

/**
 * Represents the result of a validation RPC call.
 *
 * All validation actions return this same structure, indicating either
 * successful validation or a list of validation errors.
 *
 * @example
 * // Successful validation
 * const result: ValidationResult = { success: true };
 *
 * // Failed validation
 * const result: ValidationResult = {
 *   success: false,
 *   errors: [
 *     {
 *       type: "required",
 *       message: "is required",
 *       shortMessage: "Required field",
 *       vars: { field: "email" },
 *       fields: ["email"],
 *       path: []
 *     }
 *   ]
 * };
 */
export type ValidationResult =
  | { success: true }
  | { success: false; errors: AshRpcError[]; };





export type UserUpdatedPayload = {id: UUID, email: string, name: string | null};

// Channel types for SampleProjectWeb.AccountChannel

export type AccountChannel = {
  readonly __channelType: "AccountChannel";
  on(event: string, callback: (payload: unknown) => void): number;
  off(event: string, ref: number): void;
};

export type AccountChannelEvents = {
  user_updated: UserUpdatedPayload;
};

export type AccountChannelHandlers = {
  [E in keyof AccountChannelEvents]?: (payload: AccountChannelEvents[E]) => void;
};

export type AccountChannelRefs = {
  [E in keyof AccountChannelEvents]?: number;
};