// Generated by AshTypescript - RPC Actions
// Do not edit this file manually

import { Channel } from "phoenix";

import type { AccessLogFilterInput, AccessLogResourceSchema, AccessLogSortField, AnthropicConfigFilterInput, AnthropicConfigResourceSchema, AnthropicConfigSortField, ApiKeyFilterInput, ApiKeyResourceSchema, ApiKeySortField, AshRpcError, ConditionalPaginatedResult, GcsConfigFilterInput, GcsConfigResourceSchema, GcsConfigSortField, InferResult, MemoryFilterInput, MemoryResourceSchema, MemorySortField, SortString, UUID, UnifiedFieldSelection, UserFilterInput, UserResourceSchema, UserSortField, UtcDateTimeUsec, ValidationResult } from "./ash_types";
export type * from "./ash_types";

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string | string[]; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any>;

  // HTTP customization
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Hook context
  hookCtx?: Record<string, any>;
}


/**
 * Configuration options for action channel RPC requests
 */
export interface ActionChannelConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: ReadonlyArray<string | Record<string, any>>;
  filter?: Record<string, any>;
  sort?: string | string[];
  page?:
    | {
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // Channel-specific
  channel: any; // Phoenix Channel
  resultHandler: (result: any) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;

  // Multitenancy
  tenant?: string;

  // Hook context
  hookCtx?: Record<string, any>;
}


/**
 * Configuration options for validation channel RPC requests
 */
export interface ValidationChannelConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;

  // Channel-specific
  channel: any; // Phoenix Channel
  resultHandler: (result: any) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;

  // Multitenancy
  tenant?: string;

  // Hook context
  hookCtx?: Record<string, any>;
}


/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
export async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making action channel push requests
 * Handles hooks and channel push with receive handlers
 * @param config Configuration matching ActionChannelConfig
 */
export async function executeActionChannelPush<T>(
  channel: any,
  payload: Record<string, any>,
  timeout: number | undefined,
  config: ActionChannelConfig
) {
    const processedConfig = config;

  const effectiveTimeout = timeout;

  channel
    .push("run", payload, effectiveTimeout)
    .receive("ok", async (result: T) => {

      config.resultHandler(result);
    })
    .receive("error", async (error: any) => {

      (config.errorHandler
        ? config.errorHandler
        : (error: any) => {
            console.error(
              `An error occurred while running action ${payload.action}:`,
              error
            );
          })(error);
    })
    .receive("timeout", async () => {

      (config.timeoutHandler
        ? config.timeoutHandler
        : () => {
            console.error(`Timeout occurred while running action ${payload.action}`);
          })();
    });
}


/**
 * Internal helper function for making validation channel push requests
 * Handles hooks and channel push with receive handlers
 * @param config Configuration matching ValidationChannelConfig
 */
export async function executeValidationChannelPush<T>(
  channel: any,
  payload: Record<string, any>,
  timeout: number | undefined,
  config: ValidationChannelConfig
) {
    const processedConfig = config;

  const effectiveTimeout = timeout;

  channel
    .push("validate", payload, effectiveTimeout)
    .receive("ok", async (result: T) => {

      config.resultHandler(result);
    })
    .receive("error", async (error: any) => {

      (config.errorHandler
        ? config.errorHandler
        : (error: any) => {
            console.error(
              `An error occurred while running action ${payload.action}:`,
              error
            );
          })(error);
    })
    .receive("timeout", async () => {

      (config.timeoutHandler
        ? config.timeoutHandler
        : () => {
            console.error(`Timeout occurred while running action ${payload.action}`);
          })();
    });
}



export type DestroyApiKeyResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a ApiKey
 *
 * @ashActionType :destroy
 */
export async function destroyApiKey(
  config: {
  tenant?: string;
  identity: UUID;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DestroyApiKeyResult> {
  const payload = {
    action: "destroy_api_key",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DestroyApiKeyResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a ApiKey
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDestroyApiKey(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "destroy_api_key",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a ApiKey
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDestroyApiKeyChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "destroy_api_key",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


/**
 * Delete a ApiKey
 *
 * @ashActionType :destroy
 */
export async function destroyApiKeyChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  resultHandler: (result: DestroyApiKeyResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<DestroyApiKeyResult>(
    config.channel,
    {
    action: "destroy_api_key",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


export type GenerateApiKeyInput = {
  name?: string | null;
  expiresAt: UtcDateTimeUsec;
};

export type GenerateApiKeyFields = UnifiedFieldSelection<ApiKeyResourceSchema>[];

export type GenerateApiKeyMetadata = {
  plaintextApiKey: string;
};

export type InferGenerateApiKeyResult<
  Fields extends GenerateApiKeyFields | undefined,
  MetadataFields extends ReadonlyArray<keyof GenerateApiKeyMetadata> = []
> = InferResult<ApiKeyResourceSchema, Fields>;

export type GenerateApiKeyResult<Fields extends GenerateApiKeyFields | undefined = undefined, MetadataFields extends ReadonlyArray<keyof GenerateApiKeyMetadata> = []> = | { success: true; data: InferGenerateApiKeyResult<Fields>; metadata: Pick<GenerateApiKeyMetadata, MetadataFields[number]>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new ApiKey
 *
 * @ashActionType :create
 */
export async function generateApiKey<Fields extends GenerateApiKeyFields | undefined = undefined, MetadataFields extends ReadonlyArray<keyof GenerateApiKeyMetadata> = []>(
  config: {
  tenant?: string;
  input: GenerateApiKeyInput;
  fields?: Fields;
  metadataFields?: MetadataFields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GenerateApiKeyResult<Fields extends undefined ? [] : Fields, MetadataFields>> {
  const payload = {
    action: "generate_api_key",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.metadataFields && { metadataFields: config.metadataFields })
  };

  return executeActionRpcRequest<GenerateApiKeyResult<Fields extends undefined ? [] : Fields, MetadataFields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new ApiKey
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateGenerateApiKey(
  config: {
  tenant?: string;
  input: GenerateApiKeyInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "generate_api_key",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Create a new ApiKey
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateGenerateApiKeyChannel(config: {
  channel: Channel;
  tenant?: string;
  input: GenerateApiKeyInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "generate_api_key",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Create a new ApiKey
 *
 * @ashActionType :create
 */
export async function generateApiKeyChannel<Fields extends GenerateApiKeyFields | undefined = undefined, MetadataFields extends ReadonlyArray<keyof GenerateApiKeyMetadata> = []>(config: {
  channel: Channel;
  tenant?: string;
  input: GenerateApiKeyInput;
  fields?: Fields;
  metadataFields?: MetadataFields;
  resultHandler: (result: GenerateApiKeyResult<Fields, MetadataFields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<GenerateApiKeyResult<Fields, MetadataFields>>(
    config.channel,
    {
    action: "generate_api_key",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.metadataFields && { metadataFields: config.metadataFields })
  },
    config.timeout,
    config
  );
}


export type ListApiKeysFields = UnifiedFieldSelection<ApiKeyResourceSchema>[];
export type InferListApiKeysResult<
  Fields extends ListApiKeysFields,
> = Array<InferResult<ApiKeyResourceSchema, Fields>>;

export type ListApiKeysResult<Fields extends ListApiKeysFields> = | { success: true; data: InferListApiKeysResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read ApiKey records
 *
 * @ashActionType :read
 */
export async function listApiKeys<Fields extends ListApiKeysFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: ApiKeyFilterInput;
  sort?: SortString<ApiKeySortField> | SortString<ApiKeySortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListApiKeysResult<Fields>> {
  const payload = {
    action: "list_api_keys",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListApiKeysResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read ApiKey records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListApiKeys(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_api_keys",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read ApiKey records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListApiKeysChannel(config: {
  channel: Channel;
  tenant?: string;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "list_api_keys",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


/**
 * Read ApiKey records
 *
 * @ashActionType :read
 */
export async function listApiKeysChannel<Fields extends ListApiKeysFields>(config: {
  channel: Channel;
  tenant?: string;
  fields: Fields;
  filter?: ApiKeyFilterInput;
  sort?: SortString<ApiKeySortField> | SortString<ApiKeySortField>[];
  resultHandler: (result: ListApiKeysResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ListApiKeysResult<Fields>>(
    config.channel,
    {
    action: "list_api_keys",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  },
    config.timeout,
    config
  );
}


export type ActivateUserFields = UnifiedFieldSelection<UserResourceSchema>[];

export type InferActivateUserResult<
  Fields extends ActivateUserFields | undefined,
> = InferResult<UserResourceSchema, Fields>;

export type ActivateUserResult<Fields extends ActivateUserFields | undefined = undefined> = | { success: true; data: InferActivateUserResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing User
 *
 * @ashActionType :update
 */
export async function activateUser<Fields extends ActivateUserFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ActivateUserResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "activate_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ActivateUserResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing User
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateActivateUser(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "activate_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing User
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateActivateUserChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "activate_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


/**
 * Update an existing User
 *
 * @ashActionType :update
 */
export async function activateUserChannel<Fields extends ActivateUserFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  fields?: Fields;
  resultHandler: (result: ActivateUserResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ActivateUserResult<Fields>>(
    config.channel,
    {
    action: "activate_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type DeactivateUserFields = UnifiedFieldSelection<UserResourceSchema>[];

export type InferDeactivateUserResult<
  Fields extends DeactivateUserFields | undefined,
> = InferResult<UserResourceSchema, Fields>;

export type DeactivateUserResult<Fields extends DeactivateUserFields | undefined = undefined> = | { success: true; data: InferDeactivateUserResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing User
 *
 * @ashActionType :update
 */
export async function deactivateUser<Fields extends DeactivateUserFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DeactivateUserResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "deactivate_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<DeactivateUserResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing User
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateDeactivateUser(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "deactivate_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing User
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateDeactivateUserChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "deactivate_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


/**
 * Update an existing User
 *
 * @ashActionType :update
 */
export async function deactivateUserChannel<Fields extends DeactivateUserFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  fields?: Fields;
  resultHandler: (result: DeactivateUserResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<DeactivateUserResult<Fields>>(
    config.channel,
    {
    action: "deactivate_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type GetCurrentUserFields = UnifiedFieldSelection<UserResourceSchema>[];
export type InferGetCurrentUserResult<
  Fields extends GetCurrentUserFields,
> = InferResult<UserResourceSchema, Fields>;

export type GetCurrentUserResult<Fields extends GetCurrentUserFields> = | { success: true; data: InferGetCurrentUserResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function getCurrentUser<Fields extends GetCurrentUserFields>(
  config: {
  tenant?: string;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetCurrentUserResult<Fields>> {
  const payload = {
    action: "get_current_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetCurrentUserResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetCurrentUser(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_current_user",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetCurrentUserChannel(config: {
  channel: Channel;
  tenant?: string;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "get_current_user",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function getCurrentUserChannel<Fields extends GetCurrentUserFields>(config: {
  channel: Channel;
  tenant?: string;
  fields: Fields;
  resultHandler: (result: GetCurrentUserResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<GetCurrentUserResult<Fields>>(
    config.channel,
    {
    action: "get_current_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type GetUserInput = {
  id: UUID;
};

export type GetUserFields = UnifiedFieldSelection<UserResourceSchema>[];
export type InferGetUserResult<
  Fields extends GetUserFields,
> = InferResult<UserResourceSchema, Fields>;

export type GetUserResult<Fields extends GetUserFields> = | { success: true; data: InferGetUserResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function getUser<Fields extends GetUserFields>(
  config: {
  tenant?: string;
  input: GetUserInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetUserResult<Fields>> {
  const payload = {
    action: "get_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetUserResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetUser(
  config: {
  tenant?: string;
  input: GetUserInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetUserChannel(config: {
  channel: Channel;
  tenant?: string;
  input: GetUserInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "get_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function getUserChannel<Fields extends GetUserFields>(config: {
  channel: Channel;
  tenant?: string;
  input: GetUserInput;
  fields: Fields;
  resultHandler: (result: GetUserResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<GetUserResult<Fields>>(
    config.channel,
    {
    action: "get_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type InviteUserInput = {
  email: string;
  role?: "admin" | "user";
};

export type InviteUserFields = UnifiedFieldSelection<UserResourceSchema>[];

export type InferInviteUserResult<
  Fields extends InviteUserFields | undefined,
> = InferResult<UserResourceSchema, Fields>;

export type InviteUserResult<Fields extends InviteUserFields | undefined = undefined> = | { success: true; data: InferInviteUserResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new User
 *
 * @ashActionType :create
 */
export async function inviteUser<Fields extends InviteUserFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: InviteUserInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<InviteUserResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "invite_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<InviteUserResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new User
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateInviteUser(
  config: {
  tenant?: string;
  input: InviteUserInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "invite_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Create a new User
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateInviteUserChannel(config: {
  channel: Channel;
  tenant?: string;
  input: InviteUserInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "invite_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Create a new User
 *
 * @ashActionType :create
 */
export async function inviteUserChannel<Fields extends InviteUserFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  input: InviteUserInput;
  fields?: Fields;
  resultHandler: (result: InviteUserResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<InviteUserResult<Fields>>(
    config.channel,
    {
    action: "invite_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type ListUsersInput = {
  search?: string | null;
};

export type ListUsersFields = UnifiedFieldSelection<UserResourceSchema>[];


export type InferListUsersResult<
  Fields extends ListUsersFields | undefined,
  Page extends ListUsersConfig["page"] = undefined
> = ConditionalPaginatedResult<Page, Array<InferResult<UserResourceSchema, Fields>>, {
  results: Array<InferResult<UserResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListUsersConfig = {
  tenant?: string;
  input?: ListUsersInput;
  fields: ListUsersFields;
  filter?: UserFilterInput;
  sort?: SortString<UserSortField> | SortString<UserSortField>[];
  page?: {
    limit?: number;
    after?: string;
    before?: string;
    offset?: never;
    count?: never;
  };
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListUsersResult<Fields extends ListUsersFields, Page extends ListUsersConfig["page"] = undefined> = | { success: true; data: InferListUsersResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function listUsers<Fields extends ListUsersFields, Config extends ListUsersConfig = ListUsersConfig>(
  config: Config & { fields: Fields }
): Promise<ListUsersResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_users",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListUsersResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListUsers(
  config: {
  tenant?: string;
  input?: ListUsersInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_users",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListUsersChannel(config: {
  channel: Channel;
  tenant?: string;
  input?: ListUsersInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "list_users",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function listUsersChannel<Fields extends ListUsersFields>(config: {
  channel: Channel;
  tenant?: string;
  input?: ListUsersInput;
  fields: Fields;
  filter?: UserFilterInput;
  sort?: SortString<UserSortField> | SortString<UserSortField>[];
  page?: {
    limit?: number;
    after?: string;
    before?: string;
    offset?: never;
    count?: never;
  };
  resultHandler: (result: ListUsersResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ListUsersResult<Fields>>(
    config.channel,
    {
    action: "list_users",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  },
    config.timeout,
    config
  );
}


export type RequestMagicLinkInput = {
  email: string;
};

export type InferRequestMagicLinkResult = {};

export type RequestMagicLinkResult = | { success: true; data: InferRequestMagicLinkResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on User
 *
 * @ashActionType :action
 */
export async function requestMagicLink(
  config: {
  tenant?: string;
  input: RequestMagicLinkInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RequestMagicLinkResult> {
  const payload = {
    action: "request_magic_link",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<RequestMagicLinkResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on User
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRequestMagicLink(
  config: {
  tenant?: string;
  input: RequestMagicLinkInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "request_magic_link",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on User
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRequestMagicLinkChannel(config: {
  channel: Channel;
  tenant?: string;
  input: RequestMagicLinkInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "request_magic_link",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Execute generic action on User
 *
 * @ashActionType :action
 */
export async function requestMagicLinkChannel(config: {
  channel: Channel;
  tenant?: string;
  input: RequestMagicLinkInput;
  resultHandler: (result: RequestMagicLinkResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<RequestMagicLinkResult>(
    config.channel,
    {
    action: "request_magic_link",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


export type UpdateProfileInput = {
  name?: string | null;
};

export type UpdateProfileFields = UnifiedFieldSelection<UserResourceSchema>[];

export type InferUpdateProfileResult<
  Fields extends UpdateProfileFields | undefined,
> = InferResult<UserResourceSchema, Fields>;

export type UpdateProfileResult<Fields extends UpdateProfileFields | undefined = undefined> = | { success: true; data: InferUpdateProfileResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing User
 *
 * @ashActionType :update
 */
export async function updateProfile<Fields extends UpdateProfileFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input?: UpdateProfileInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateProfileResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_profile",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateProfileResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing User
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateProfile(
  config: {
  tenant?: string;
  identity: UUID | string;
  input?: UpdateProfileInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_profile",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing User
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateProfileChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  input?: UpdateProfileInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "update_profile",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Update an existing User
 *
 * @ashActionType :update
 */
export async function updateProfileChannel<Fields extends UpdateProfileFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  input?: UpdateProfileInput;
  fields?: Fields;
  resultHandler: (result: UpdateProfileResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<UpdateProfileResult<Fields>>(
    config.channel,
    {
    action: "update_profile",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type UpdateUserInput = {
  email?: string;
  role?: "admin" | "user";
  name?: string | null;
};

export type UpdateUserFields = UnifiedFieldSelection<UserResourceSchema>[];

export type InferUpdateUserResult<
  Fields extends UpdateUserFields | undefined,
> = InferResult<UserResourceSchema, Fields>;

export type UpdateUserResult<Fields extends UpdateUserFields | undefined = undefined> = | { success: true; data: InferUpdateUserResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing User
 *
 * @ashActionType :update
 */
export async function updateUser<Fields extends UpdateUserFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input: UpdateUserInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateUserResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateUserResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing User
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateUser(
  config: {
  tenant?: string;
  identity: UUID | string;
  input: UpdateUserInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing User
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateUserChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  input: UpdateUserInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "update_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Update an existing User
 *
 * @ashActionType :update
 */
export async function updateUserChannel<Fields extends UpdateUserFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  input: UpdateUserInput;
  fields?: Fields;
  resultHandler: (result: UpdateUserResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<UpdateUserResult<Fields>>(
    config.channel,
    {
    action: "update_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type ListAccessLogsInput = {
  actorId?: UUID | null;
  recordId?: UUID | null;
  projectId?: UUID | null;
  actionType?: "create" | "destroy" | "read" | "update" | null;
  actorEmail?: string | null;
  from?: UtcDateTimeUsec | null;
  to?: UtcDateTimeUsec | null;
};

export type ListAccessLogsFields = UnifiedFieldSelection<AccessLogResourceSchema>[];


export type InferListAccessLogsResult<
  Fields extends ListAccessLogsFields | undefined,
  Page extends ListAccessLogsConfig["page"] = undefined
> = ConditionalPaginatedResult<Page, Array<InferResult<AccessLogResourceSchema, Fields>>, {
  results: Array<InferResult<AccessLogResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListAccessLogsConfig = {
  tenant?: string;
  input?: ListAccessLogsInput;
  fields: ListAccessLogsFields;
  filter?: AccessLogFilterInput;
  sort?: SortString<AccessLogSortField> | SortString<AccessLogSortField>[];
  page?: {
    limit?: number;
    after?: string;
    before?: string;
    offset?: never;
    count?: never;
  };
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListAccessLogsResult<Fields extends ListAccessLogsFields, Page extends ListAccessLogsConfig["page"] = undefined> = | { success: true; data: InferListAccessLogsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read AccessLog records
 *
 * @ashActionType :read
 */
export async function listAccessLogs<Fields extends ListAccessLogsFields, Config extends ListAccessLogsConfig = ListAccessLogsConfig>(
  config: Config & { fields: Fields }
): Promise<ListAccessLogsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_access_logs",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListAccessLogsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read AccessLog records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListAccessLogs(
  config: {
  tenant?: string;
  input?: ListAccessLogsInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_access_logs",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read AccessLog records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListAccessLogsChannel(config: {
  channel: Channel;
  tenant?: string;
  input?: ListAccessLogsInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "list_access_logs",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Read AccessLog records
 *
 * @ashActionType :read
 */
export async function listAccessLogsChannel<Fields extends ListAccessLogsFields>(config: {
  channel: Channel;
  tenant?: string;
  input?: ListAccessLogsInput;
  fields: Fields;
  filter?: AccessLogFilterInput;
  sort?: SortString<AccessLogSortField> | SortString<AccessLogSortField>[];
  page?: {
    limit?: number;
    after?: string;
    before?: string;
    offset?: never;
    count?: never;
  };
  resultHandler: (result: ListAccessLogsResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ListAccessLogsResult<Fields>>(
    config.channel,
    {
    action: "list_access_logs",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  },
    config.timeout,
    config
  );
}


export type CreateMemoryInput = {
  scope: "global" | "repository" | "user";
  repoKey?: string | null;
  content: string;
};

export type CreateMemoryFields = UnifiedFieldSelection<MemoryResourceSchema>[];

export type InferCreateMemoryResult<
  Fields extends CreateMemoryFields | undefined,
> = InferResult<MemoryResourceSchema, Fields>;

export type CreateMemoryResult<Fields extends CreateMemoryFields | undefined = undefined> = | { success: true; data: InferCreateMemoryResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Memory
 *
 * @ashActionType :create
 */
export async function createMemory<Fields extends CreateMemoryFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateMemoryInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateMemoryResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateMemoryResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Memory
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateMemory(
  config: {
  tenant?: string;
  input: CreateMemoryInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Memory
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateMemoryChannel(config: {
  channel: Channel;
  tenant?: string;
  input: CreateMemoryInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "create_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Create a new Memory
 *
 * @ashActionType :create
 */
export async function createMemoryChannel<Fields extends CreateMemoryFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  input: CreateMemoryInput;
  fields?: Fields;
  resultHandler: (result: CreateMemoryResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<CreateMemoryResult<Fields>>(
    config.channel,
    {
    action: "create_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type DeleteMemoryResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Memory
 *
 * @ashActionType :destroy
 */
export async function deleteMemory(
  config: {
  tenant?: string;
  identity: UUID;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DeleteMemoryResult> {
  const payload = {
    action: "delete_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DeleteMemoryResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Memory
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDeleteMemory(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "delete_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Memory
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDeleteMemoryChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "delete_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


/**
 * Delete a Memory
 *
 * @ashActionType :destroy
 */
export async function deleteMemoryChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  resultHandler: (result: DeleteMemoryResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<DeleteMemoryResult>(
    config.channel,
    {
    action: "delete_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  },
    config.timeout,
    config
  );
}


export type GetMemoryInput = {
  id: UUID;
};

export type GetMemoryFields = UnifiedFieldSelection<MemoryResourceSchema>[];
export type InferGetMemoryResult<
  Fields extends GetMemoryFields,
> = InferResult<MemoryResourceSchema, Fields>;

export type GetMemoryResult<Fields extends GetMemoryFields> = | { success: true; data: InferGetMemoryResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Memory records
 *
 * @ashActionType :read
 */
export async function getMemory<Fields extends GetMemoryFields>(
  config: {
  tenant?: string;
  input: GetMemoryInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetMemoryResult<Fields>> {
  const payload = {
    action: "get_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetMemoryResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Memory records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetMemory(
  config: {
  tenant?: string;
  input: GetMemoryInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read Memory records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetMemoryChannel(config: {
  channel: Channel;
  tenant?: string;
  input: GetMemoryInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "get_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Read Memory records
 *
 * @ashActionType :read
 */
export async function getMemoryChannel<Fields extends GetMemoryFields>(config: {
  channel: Channel;
  tenant?: string;
  input: GetMemoryInput;
  fields: Fields;
  resultHandler: (result: GetMemoryResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<GetMemoryResult<Fields>>(
    config.channel,
    {
    action: "get_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type ListMemoriesInput = {
  scope?: "global" | "repository" | "user" | null;
  repoKey?: string | null;
  search?: string | null;
};

export type ListMemoriesFields = UnifiedFieldSelection<MemoryResourceSchema>[];


export type InferListMemoriesResult<
  Fields extends ListMemoriesFields | undefined,
  Page extends ListMemoriesConfig["page"] = undefined
> = ConditionalPaginatedResult<Page, Array<InferResult<MemoryResourceSchema, Fields>>, {
  results: Array<InferResult<MemoryResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListMemoriesConfig = {
  tenant?: string;
  input?: ListMemoriesInput;
  fields: ListMemoriesFields;
  filter?: MemoryFilterInput;
  sort?: SortString<MemorySortField> | SortString<MemorySortField>[];
  page?: {
    limit?: number;
    after?: string;
    before?: string;
    offset?: never;
    count?: never;
  };
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListMemoriesResult<Fields extends ListMemoriesFields, Page extends ListMemoriesConfig["page"] = undefined> = | { success: true; data: InferListMemoriesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Memory records
 *
 * @ashActionType :read
 */
export async function listMemories<Fields extends ListMemoriesFields, Config extends ListMemoriesConfig = ListMemoriesConfig>(
  config: Config & { fields: Fields }
): Promise<ListMemoriesResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_memories",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListMemoriesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Memory records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListMemories(
  config: {
  tenant?: string;
  input?: ListMemoriesInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_memories",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read Memory records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListMemoriesChannel(config: {
  channel: Channel;
  tenant?: string;
  input?: ListMemoriesInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "list_memories",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Read Memory records
 *
 * @ashActionType :read
 */
export async function listMemoriesChannel<Fields extends ListMemoriesFields>(config: {
  channel: Channel;
  tenant?: string;
  input?: ListMemoriesInput;
  fields: Fields;
  filter?: MemoryFilterInput;
  sort?: SortString<MemorySortField> | SortString<MemorySortField>[];
  page?: {
    limit?: number;
    after?: string;
    before?: string;
    offset?: never;
    count?: never;
  };
  resultHandler: (result: ListMemoriesResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ListMemoriesResult<Fields>>(
    config.channel,
    {
    action: "list_memories",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  },
    config.timeout,
    config
  );
}


export type SearchMemoriesInput = {
  query: string;
  scope?: "global" | "repository" | "user" | null;
  repoKey?: string | null;
  limit?: number;
};

export type SearchMemoriesFields = UnifiedFieldSelection<MemoryResourceSchema>[];
export type InferSearchMemoriesResult<
  Fields extends SearchMemoriesFields,
> = Array<InferResult<MemoryResourceSchema, Fields>>;

export type SearchMemoriesResult<Fields extends SearchMemoriesFields> = | { success: true; data: InferSearchMemoriesResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Memory records
 *
 * @ashActionType :read
 */
export async function searchMemories<Fields extends SearchMemoriesFields>(
  config: {
  tenant?: string;
  input: SearchMemoriesInput;
  fields: Fields;
  filter?: MemoryFilterInput;
  sort?: SortString<MemorySortField> | SortString<MemorySortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<SearchMemoriesResult<Fields>> {
  const payload = {
    action: "search_memories",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<SearchMemoriesResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Memory records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateSearchMemories(
  config: {
  tenant?: string;
  input: SearchMemoriesInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "search_memories",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read Memory records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateSearchMemoriesChannel(config: {
  channel: Channel;
  tenant?: string;
  input: SearchMemoriesInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "search_memories",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Read Memory records
 *
 * @ashActionType :read
 */
export async function searchMemoriesChannel<Fields extends SearchMemoriesFields>(config: {
  channel: Channel;
  tenant?: string;
  input: SearchMemoriesInput;
  fields: Fields;
  filter?: MemoryFilterInput;
  sort?: SortString<MemorySortField> | SortString<MemorySortField>[];
  resultHandler: (result: SearchMemoriesResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<SearchMemoriesResult<Fields>>(
    config.channel,
    {
    action: "search_memories",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  },
    config.timeout,
    config
  );
}


export type UpdateMemoryInput = {
  content?: string;
  repoKey?: string | null;
};

export type UpdateMemoryFields = UnifiedFieldSelection<MemoryResourceSchema>[];

export type InferUpdateMemoryResult<
  Fields extends UpdateMemoryFields | undefined,
> = InferResult<MemoryResourceSchema, Fields>;

export type UpdateMemoryResult<Fields extends UpdateMemoryFields | undefined = undefined> = | { success: true; data: InferUpdateMemoryResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Memory
 *
 * @ashActionType :update
 */
export async function updateMemory<Fields extends UpdateMemoryFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input: UpdateMemoryInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateMemoryResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateMemoryResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Memory
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateMemory(
  config: {
  tenant?: string;
  identity: UUID | string;
  input: UpdateMemoryInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Memory
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateMemoryChannel(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID | string;
  input: UpdateMemoryInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "update_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Update an existing Memory
 *
 * @ashActionType :update
 */
export async function updateMemoryChannel<Fields extends UpdateMemoryFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  identity: UUID;
  input: UpdateMemoryInput;
  fields?: Fields;
  resultHandler: (result: UpdateMemoryResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<UpdateMemoryResult<Fields>>(
    config.channel,
    {
    action: "update_memory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type GetAnthropicConfigFields = UnifiedFieldSelection<AnthropicConfigResourceSchema>[];
export type InferGetAnthropicConfigResult<
  Fields extends GetAnthropicConfigFields,
> = Array<InferResult<AnthropicConfigResourceSchema, Fields>>;

export type GetAnthropicConfigResult<Fields extends GetAnthropicConfigFields> = | { success: true; data: InferGetAnthropicConfigResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read AnthropicConfig records
 *
 * @ashActionType :read
 */
export async function getAnthropicConfig<Fields extends GetAnthropicConfigFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: AnthropicConfigFilterInput;
  sort?: SortString<AnthropicConfigSortField> | SortString<AnthropicConfigSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetAnthropicConfigResult<Fields>> {
  const payload = {
    action: "get_anthropic_config",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<GetAnthropicConfigResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read AnthropicConfig records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetAnthropicConfig(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_anthropic_config",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read AnthropicConfig records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetAnthropicConfigChannel(config: {
  channel: Channel;
  tenant?: string;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "get_anthropic_config",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


/**
 * Read AnthropicConfig records
 *
 * @ashActionType :read
 */
export async function getAnthropicConfigChannel<Fields extends GetAnthropicConfigFields>(config: {
  channel: Channel;
  tenant?: string;
  fields: Fields;
  filter?: AnthropicConfigFilterInput;
  sort?: SortString<AnthropicConfigSortField> | SortString<AnthropicConfigSortField>[];
  resultHandler: (result: GetAnthropicConfigResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<GetAnthropicConfigResult<Fields>>(
    config.channel,
    {
    action: "get_anthropic_config",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  },
    config.timeout,
    config
  );
}


export type ListAnthropicModelsFields = UnifiedFieldSelection<{id: string, displayName: string, __type: "TypedMap", __primitiveFields: "id" | "displayName"}>[];

export type InferListAnthropicModelsResult<
  Fields extends ListAnthropicModelsFields | undefined,
> = Array<InferResult<{id: string, displayName: string, __type: "TypedMap", __primitiveFields: "id" | "displayName"}, Fields>>;

export type ListAnthropicModelsResult<Fields extends ListAnthropicModelsFields | undefined = undefined> = | { success: true; data: InferListAnthropicModelsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on AnthropicConfig
 *
 * @ashActionType :action
 */
export async function listAnthropicModels<Fields extends ListAnthropicModelsFields | undefined = undefined>(
  config: {
  tenant?: string;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListAnthropicModelsResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "list_anthropic_models",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ListAnthropicModelsResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on AnthropicConfig
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateListAnthropicModels(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_anthropic_models",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on AnthropicConfig
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateListAnthropicModelsChannel(config: {
  channel: Channel;
  tenant?: string;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "list_anthropic_models",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


/**
 * Execute generic action on AnthropicConfig
 *
 * @ashActionType :action
 */
export async function listAnthropicModelsChannel<Fields extends ListAnthropicModelsFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  fields: Fields;
  resultHandler: (result: ListAnthropicModelsResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<ListAnthropicModelsResult<Fields>>(
    config.channel,
    {
    action: "list_anthropic_models",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type SetAnthropicConfigInput = {
  defaultModel?: string | null;
  apiKey?: string | null;
};

export type SetAnthropicConfigFields = UnifiedFieldSelection<AnthropicConfigResourceSchema>[];

export type InferSetAnthropicConfigResult<
  Fields extends SetAnthropicConfigFields | undefined,
> = InferResult<AnthropicConfigResourceSchema, Fields>;

export type SetAnthropicConfigResult<Fields extends SetAnthropicConfigFields | undefined = undefined> = | { success: true; data: InferSetAnthropicConfigResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new AnthropicConfig
 *
 * @ashActionType :create
 */
export async function setAnthropicConfig<Fields extends SetAnthropicConfigFields | undefined = undefined>(
  config: {
  tenant?: string;
  input?: SetAnthropicConfigInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<SetAnthropicConfigResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "set_anthropic_config",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<SetAnthropicConfigResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new AnthropicConfig
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateSetAnthropicConfig(
  config: {
  tenant?: string;
  input?: SetAnthropicConfigInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "set_anthropic_config",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Create a new AnthropicConfig
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateSetAnthropicConfigChannel(config: {
  channel: Channel;
  tenant?: string;
  input?: SetAnthropicConfigInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "set_anthropic_config",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Create a new AnthropicConfig
 *
 * @ashActionType :create
 */
export async function setAnthropicConfigChannel<Fields extends SetAnthropicConfigFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  input?: SetAnthropicConfigInput;
  fields?: Fields;
  resultHandler: (result: SetAnthropicConfigResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<SetAnthropicConfigResult<Fields>>(
    config.channel,
    {
    action: "set_anthropic_config",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}


export type GetGcsConfigFields = UnifiedFieldSelection<GcsConfigResourceSchema>[];
export type InferGetGcsConfigResult<
  Fields extends GetGcsConfigFields,
> = Array<InferResult<GcsConfigResourceSchema, Fields>>;

export type GetGcsConfigResult<Fields extends GetGcsConfigFields> = | { success: true; data: InferGetGcsConfigResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read GcsConfig records
 *
 * @ashActionType :read
 */
export async function getGcsConfig<Fields extends GetGcsConfigFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: GcsConfigFilterInput;
  sort?: SortString<GcsConfigSortField> | SortString<GcsConfigSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetGcsConfigResult<Fields>> {
  const payload = {
    action: "get_gcs_config",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<GetGcsConfigResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read GcsConfig records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetGcsConfig(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_gcs_config",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Read GcsConfig records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetGcsConfigChannel(config: {
  channel: Channel;
  tenant?: string;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "get_gcs_config",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  },
    config.timeout,
    config
  );
}


/**
 * Read GcsConfig records
 *
 * @ashActionType :read
 */
export async function getGcsConfigChannel<Fields extends GetGcsConfigFields>(config: {
  channel: Channel;
  tenant?: string;
  fields: Fields;
  filter?: GcsConfigFilterInput;
  sort?: SortString<GcsConfigSortField> | SortString<GcsConfigSortField>[];
  resultHandler: (result: GetGcsConfigResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<GetGcsConfigResult<Fields>>(
    config.channel,
    {
    action: "get_gcs_config",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  },
    config.timeout,
    config
  );
}


export type SetGcsConfigInput = {
  bucketName?: string | null;
  serviceAccountJson?: string | null;
};

export type SetGcsConfigFields = UnifiedFieldSelection<GcsConfigResourceSchema>[];

export type InferSetGcsConfigResult<
  Fields extends SetGcsConfigFields | undefined,
> = InferResult<GcsConfigResourceSchema, Fields>;

export type SetGcsConfigResult<Fields extends SetGcsConfigFields | undefined = undefined> = | { success: true; data: InferSetGcsConfigResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new GcsConfig
 *
 * @ashActionType :create
 */
export async function setGcsConfig<Fields extends SetGcsConfigFields | undefined = undefined>(
  config: {
  tenant?: string;
  input?: SetGcsConfigInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<SetGcsConfigResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "set_gcs_config",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<SetGcsConfigResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new GcsConfig
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateSetGcsConfig(
  config: {
  tenant?: string;
  input?: SetGcsConfigInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "set_gcs_config",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


/**
 * Validate: Create a new GcsConfig
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateSetGcsConfigChannel(config: {
  channel: Channel;
  tenant?: string;
  input?: SetGcsConfigInput;
  resultHandler: (result: ValidationResult) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeValidationChannelPush<ValidationResult>(
    config.channel,
    {
    action: "set_gcs_config",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  },
    config.timeout,
    config
  );
}


/**
 * Create a new GcsConfig
 *
 * @ashActionType :create
 */
export async function setGcsConfigChannel<Fields extends SetGcsConfigFields | undefined = undefined>(config: {
  channel: Channel;
  tenant?: string;
  input?: SetGcsConfigInput;
  fields?: Fields;
  resultHandler: (result: SetGcsConfigResult<Fields>) => void;
  errorHandler?: (error: any) => void;
  timeoutHandler?: () => void;
  timeout?: number;
}) {
  executeActionChannelPush<SetGcsConfigResult<Fields>>(
    config.channel,
    {
    action: "set_gcs_config",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  },
    config.timeout,
    config
  );
}

