/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppMeRouteImport } from './routes/app/me'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppAdminGcsRouteImport } from './routes/app/admin/gcs'
import { Route as AppAdminAiRouteImport } from './routes/app/admin/ai'
import { Route as AppAdminUsersIndexRouteImport } from './routes/app/admin/users/index'
import { Route as AppAdminMemoriesIndexRouteImport } from './routes/app/admin/memories/index'
import { Route as AppAdminAccessLogIndexRouteImport } from './routes/app/admin/access-log/index'
import { Route as AppAdminMemoriesNewRouteImport } from './routes/app/admin/memories/new'
import { Route as AppAdminAccessLogLogIdRouteImport } from './routes/app/admin/access-log/$logId'
import { Route as AppAdminUsersUserIdIndexRouteImport } from './routes/app/admin/users/$userId/index'
import { Route as AppAdminMemoriesMemoryIdIndexRouteImport } from './routes/app/admin/memories/$memoryId/index'
import { Route as AppAdminUsersUserIdEditRouteImport } from './routes/app/admin/users/$userId/edit'
import { Route as AppAdminMemoriesMemoryIdEditRouteImport } from './routes/app/admin/memories/$memoryId/edit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminGcsRoute = AppAdminGcsRouteImport.update({
  id: '/gcs',
  path: '/gcs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAiRoute = AppAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMemoriesIndexRoute = AppAdminMemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAccessLogIndexRoute = AppAdminAccessLogIndexRouteImport.update({
  id: '/access-log/',
  path: '/access-log/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMemoriesNewRoute = AppAdminMemoriesNewRouteImport.update({
  id: '/memories/new',
  path: '/memories/new',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAccessLogLogIdRoute = AppAdminAccessLogLogIdRouteImport.update({
  id: '/access-log/$logId',
  path: '/access-log/$logId',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersUserIdIndexRoute =
  AppAdminUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminMemoriesMemoryIdIndexRoute =
  AppAdminMemoriesMemoryIdIndexRouteImport.update({
    id: '/memories/$memoryId/',
    path: '/memories/$memoryId/',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminUsersUserIdEditRoute = AppAdminUsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMemoriesMemoryIdEditRoute =
  AppAdminMemoriesMemoryIdEditRouteImport.update({
    id: '/memories/$memoryId/edit',
    path: '/memories/$memoryId/edit',
    getParentRoute: () => AppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/me': typeof AppMeRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/ai': typeof AppAdminAiRoute
  '/app/admin/gcs': typeof AppAdminGcsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/admin/access-log/$logId': typeof AppAdminAccessLogLogIdRoute
  '/app/admin/memories/new': typeof AppAdminMemoriesNewRoute
  '/app/admin/access-log/': typeof AppAdminAccessLogIndexRoute
  '/app/admin/memories/': typeof AppAdminMemoriesIndexRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
  '/app/admin/memories/$memoryId/edit': typeof AppAdminMemoriesMemoryIdEditRoute
  '/app/admin/users/$userId/edit': typeof AppAdminUsersUserIdEditRoute
  '/app/admin/memories/$memoryId/': typeof AppAdminMemoriesMemoryIdIndexRoute
  '/app/admin/users/$userId/': typeof AppAdminUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/app/me': typeof AppMeRoute
  '/app': typeof AppIndexRoute
  '/app/admin/ai': typeof AppAdminAiRoute
  '/app/admin/gcs': typeof AppAdminGcsRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/admin/access-log/$logId': typeof AppAdminAccessLogLogIdRoute
  '/app/admin/memories/new': typeof AppAdminMemoriesNewRoute
  '/app/admin/access-log': typeof AppAdminAccessLogIndexRoute
  '/app/admin/memories': typeof AppAdminMemoriesIndexRoute
  '/app/admin/users': typeof AppAdminUsersIndexRoute
  '/app/admin/memories/$memoryId/edit': typeof AppAdminMemoriesMemoryIdEditRoute
  '/app/admin/users/$userId/edit': typeof AppAdminUsersUserIdEditRoute
  '/app/admin/memories/$memoryId': typeof AppAdminMemoriesMemoryIdIndexRoute
  '/app/admin/users/$userId': typeof AppAdminUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/me': typeof AppMeRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/ai': typeof AppAdminAiRoute
  '/app/admin/gcs': typeof AppAdminGcsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/admin/access-log/$logId': typeof AppAdminAccessLogLogIdRoute
  '/app/admin/memories/new': typeof AppAdminMemoriesNewRoute
  '/app/admin/access-log/': typeof AppAdminAccessLogIndexRoute
  '/app/admin/memories/': typeof AppAdminMemoriesIndexRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
  '/app/admin/memories/$memoryId/edit': typeof AppAdminMemoriesMemoryIdEditRoute
  '/app/admin/users/$userId/edit': typeof AppAdminUsersUserIdEditRoute
  '/app/admin/memories/$memoryId/': typeof AppAdminMemoriesMemoryIdIndexRoute
  '/app/admin/users/$userId/': typeof AppAdminUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/admin'
    | '/app/me'
    | '/app/'
    | '/app/admin/ai'
    | '/app/admin/gcs'
    | '/app/admin/'
    | '/app/admin/access-log/$logId'
    | '/app/admin/memories/new'
    | '/app/admin/access-log/'
    | '/app/admin/memories/'
    | '/app/admin/users/'
    | '/app/admin/memories/$memoryId/edit'
    | '/app/admin/users/$userId/edit'
    | '/app/admin/memories/$memoryId/'
    | '/app/admin/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/app/me'
    | '/app'
    | '/app/admin/ai'
    | '/app/admin/gcs'
    | '/app/admin'
    | '/app/admin/access-log/$logId'
    | '/app/admin/memories/new'
    | '/app/admin/access-log'
    | '/app/admin/memories'
    | '/app/admin/users'
    | '/app/admin/memories/$memoryId/edit'
    | '/app/admin/users/$userId/edit'
    | '/app/admin/memories/$memoryId'
    | '/app/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/admin'
    | '/app/me'
    | '/app/'
    | '/app/admin/ai'
    | '/app/admin/gcs'
    | '/app/admin/'
    | '/app/admin/access-log/$logId'
    | '/app/admin/memories/new'
    | '/app/admin/access-log/'
    | '/app/admin/memories/'
    | '/app/admin/users/'
    | '/app/admin/memories/$memoryId/edit'
    | '/app/admin/users/$userId/edit'
    | '/app/admin/memories/$memoryId/'
    | '/app/admin/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/gcs': {
      id: '/app/admin/gcs'
      path: '/gcs'
      fullPath: '/app/admin/gcs'
      preLoaderRoute: typeof AppAdminGcsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/ai': {
      id: '/app/admin/ai'
      path: '/ai'
      fullPath: '/app/admin/ai'
      preLoaderRoute: typeof AppAdminAiRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/users/': {
      id: '/app/admin/users/'
      path: '/users'
      fullPath: '/app/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/memories/': {
      id: '/app/admin/memories/'
      path: '/memories'
      fullPath: '/app/admin/memories/'
      preLoaderRoute: typeof AppAdminMemoriesIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/access-log/': {
      id: '/app/admin/access-log/'
      path: '/access-log'
      fullPath: '/app/admin/access-log/'
      preLoaderRoute: typeof AppAdminAccessLogIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/memories/new': {
      id: '/app/admin/memories/new'
      path: '/memories/new'
      fullPath: '/app/admin/memories/new'
      preLoaderRoute: typeof AppAdminMemoriesNewRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/access-log/$logId': {
      id: '/app/admin/access-log/$logId'
      path: '/access-log/$logId'
      fullPath: '/app/admin/access-log/$logId'
      preLoaderRoute: typeof AppAdminAccessLogLogIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/users/$userId/': {
      id: '/app/admin/users/$userId/'
      path: '/users/$userId'
      fullPath: '/app/admin/users/$userId/'
      preLoaderRoute: typeof AppAdminUsersUserIdIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/memories/$memoryId/': {
      id: '/app/admin/memories/$memoryId/'
      path: '/memories/$memoryId'
      fullPath: '/app/admin/memories/$memoryId/'
      preLoaderRoute: typeof AppAdminMemoriesMemoryIdIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/users/$userId/edit': {
      id: '/app/admin/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/app/admin/users/$userId/edit'
      preLoaderRoute: typeof AppAdminUsersUserIdEditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/memories/$memoryId/edit': {
      id: '/app/admin/memories/$memoryId/edit'
      path: '/memories/$memoryId/edit'
      fullPath: '/app/admin/memories/$memoryId/edit'
      preLoaderRoute: typeof AppAdminMemoriesMemoryIdEditRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAiRoute: typeof AppAdminAiRoute
  AppAdminGcsRoute: typeof AppAdminGcsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminAccessLogLogIdRoute: typeof AppAdminAccessLogLogIdRoute
  AppAdminMemoriesNewRoute: typeof AppAdminMemoriesNewRoute
  AppAdminAccessLogIndexRoute: typeof AppAdminAccessLogIndexRoute
  AppAdminMemoriesIndexRoute: typeof AppAdminMemoriesIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
  AppAdminMemoriesMemoryIdEditRoute: typeof AppAdminMemoriesMemoryIdEditRoute
  AppAdminUsersUserIdEditRoute: typeof AppAdminUsersUserIdEditRoute
  AppAdminMemoriesMemoryIdIndexRoute: typeof AppAdminMemoriesMemoryIdIndexRoute
  AppAdminUsersUserIdIndexRoute: typeof AppAdminUsersUserIdIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAiRoute: AppAdminAiRoute,
  AppAdminGcsRoute: AppAdminGcsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminAccessLogLogIdRoute: AppAdminAccessLogLogIdRoute,
  AppAdminMemoriesNewRoute: AppAdminMemoriesNewRoute,
  AppAdminAccessLogIndexRoute: AppAdminAccessLogIndexRoute,
  AppAdminMemoriesIndexRoute: AppAdminMemoriesIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
  AppAdminMemoriesMemoryIdEditRoute: AppAdminMemoriesMemoryIdEditRoute,
  AppAdminUsersUserIdEditRoute: AppAdminUsersUserIdEditRoute,
  AppAdminMemoriesMemoryIdIndexRoute: AppAdminMemoriesMemoryIdIndexRoute,
  AppAdminUsersUserIdIndexRoute: AppAdminUsersUserIdIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppMeRoute: typeof AppMeRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppMeRoute: AppMeRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
