defmodule SampleProjectWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample_project

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_sample_project_key",
    signing_salt: "r5jWm80Z",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Realtime channels for the React SPA. Authenticated via a signed token the
  # SPA shell embeds (derived from the session user) — see SampleProjectWeb.UserSocket.
  socket "/socket", SampleProjectWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Kubernetes health probes. Kept at the top of the pipeline so the frequent
  # probe requests don't generate log noise or telemetry. Serves
  # /healthz/{startup,liveness,readiness} via SampleProject.Health.
  plug KubernetesHealthCheck.Plug,
    mod: SampleProject.Health,
    base_path: "/healthz"

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :sample_project,
    gzip: not code_reloading?,
    only: SampleProjectWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  if Mix.env() == :dev do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :sample_project
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    # Allow up to 100 MB multipart bodies for file uploads. The limit is scoped to
    # :multipart so JSON/RPC request bodies stay bounded by Plug's default.
    parsers: [:urlencoded, {:multipart, length: 104_857_600}, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug SampleProjectWeb.Router
end
