import Config
config :ash, policies: [show_policy_breakdowns?: true]

# Default local dev to the model-free stub adapter so a fresh checkout doesn't
# download ~130 MB of weights or compile EXLA. To exercise the real embeddings
# (e.g. before shipping), run with `EMBEDDINGS_REAL=1 mix phx.server`.
if System.get_env("EMBEDDINGS_REAL") in ~w(1 true) do
  config :sample_project, :embeddings, adapter: SampleProject.Embeddings.ServingAdapter
  config :nx, :default_backend, EXLA.Backend
else
  config :sample_project, :embeddings, adapter: SampleProject.Embeddings.StubAdapter
  config :nx, :default_backend, Nx.BinaryBackend
end

# Cloak vault key for development. This is a throwaway key; production reads its
# key from the CLOAK_KEY environment variable (see config/runtime.exs).
config :sample_project, SampleProject.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1",
       key: Base.decode64!("t53NIdZqrTMK9zg7gDzWWCr7A2o/4wSoMsSsHZoBQ9Y="),
       iv_length: 12}
  ]

# Configure your database
config :sample_project, SampleProject.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "sample_project_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  # Encode/decode pgvector `vector` columns as Ash.Vector (see SampleProject.PostgrexTypes).
  types: SampleProject.PostgrexTypes

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sample_project, SampleProjectWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "P1x9J1elWp/tr3kgKzpPOsipvbUenJkLb3+kvQeXtnzA5eksO6vGJsCQwKQWL80R",
  watchers: [
    # `run-vite.mjs` wraps Vite so it exits when Phoenix closes the watcher's
    # stdin; otherwise stopping the server orphans Vite and it keeps port 5173.
    node: [
      "run-vite.mjs",
      "--clearScreen",
      "false",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# In development the Vite dev server (port 5173) serves JS/CSS with HMR; the
# Phoenix-rendered SPA shell loads modules from it (see SampleProjectWeb.Vite).
config :sample_project, :vite_dev_server, "http://localhost:5173"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :sample_project, SampleProjectWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/sample_project_web/router\.ex$"E,
      ~r"lib/sample_project_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :sample_project, dev_routes: true, token_signing_secret: "lcRLD+hXGfvTZsLIs0mQFI8feSEZB7ff"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
