defmodule SampleProject.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :name, :text
      add :role, :text, null: false, default: "user"
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:memories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :scope, :text, null: false
      add :repo_key, :text
      add :content, :text, null: false
      add :content_hash, :text
      add :embedding, :vector, size: 384

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_by_id,
          references(:users,
            column: :id,
            name: "memories_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:memories, [:created_by_id])

    create index(:memories, [:repo_key])

    create index(:memories, [:scope])

    create table(:gcs_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :singleton, :text, null: false, default: "singleton"
      add :bucket_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_service_account_json, :binary
    end

    create unique_index(:gcs_configs, [:singleton], name: "gcs_configs_singleton_index")

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :api_key_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")

    create table(:anthropic_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :singleton, :text, null: false, default: "singleton"
      add :default_model, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_api_key, :binary
    end

    create unique_index(:anthropic_configs, [:singleton],
             name: "anthropic_configs_singleton_index"
           )

    create table(:access_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action_type, :text, null: false
      add :action_name, :text, null: false
      add :resource_type, :text, null: false
      add :record_id, :uuid
      add :project_id, :uuid
      add :actor_id, :uuid
      add :actor_email, :text
      add :ip_address, :text
      add :user_agent, :text
      add :request_id, :text
      add :request_path, :text
      add :page_view_id, :text
      add :occurred_at, :utc_datetime_usec, null: false
    end

    create index(:access_logs, [:page_view_id])

    create index(:access_logs, [:occurred_at])

    create index(:access_logs, [:project_id])

    create index(:access_logs, [:actor_id])

    create index(:access_logs, [:record_id])

    execute("""
    CREATE INDEX memories_embedding_hnsw_index
      ON memories
      USING hnsw (embedding vector_cosine_ops)
      WITH (m = 16, ef_construction = 64)
    """)
  end

  def down do
    execute("""
    DROP INDEX IF EXISTS memories_embedding_hnsw_index
    """)

    drop_if_exists index(:access_logs, [:record_id])

    drop_if_exists index(:access_logs, [:actor_id])

    drop_if_exists index(:access_logs, [:project_id])

    drop_if_exists index(:access_logs, [:occurred_at])

    drop_if_exists index(:access_logs, [:page_view_id])

    drop table(:access_logs)

    drop_if_exists unique_index(:anthropic_configs, [:singleton],
                     name: "anthropic_configs_singleton_index"
                   )

    drop table(:anthropic_configs)

    drop constraint(:api_keys, "api_keys_user_id_fkey")

    drop_if_exists unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")

    drop table(:api_keys)

    drop_if_exists unique_index(:gcs_configs, [:singleton], name: "gcs_configs_singleton_index")

    drop table(:gcs_configs)

    drop constraint(:memories, "memories_created_by_id_fkey")

    drop_if_exists index(:memories, [:scope])

    drop_if_exists index(:memories, [:repo_key])

    drop_if_exists index(:memories, [:created_by_id])

    drop table(:memories)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
